In [3]:
import tensorflow as tf

# Set the random seed
tf.random.set_seed(42)

# Generate some random numbers
a = tf.random.normal([1])
b = tf.random.normal([1])

# Check that the results are the same every time
print(a)
print(b)

tf.Tensor([0.3274685], shape=(1,), dtype=float32)
tf.Tensor([0.08422458], shape=(1,), dtype=float32)


In [9]:
import tensorflow as tf

# Generate some random numbers with a specific seed
a = tf.random.normal([1], seed=42)
b = tf.random.normal([1], seed=42)

# Check that the results are the same every time
print(a)
print(b)

tf.Tensor([0.457556], shape=(1,), dtype=float32)
tf.Tensor([1.2668815], shape=(1,), dtype=float32)
